#!/bin/sh /etc/rc.common
START=50

run_rewan()
{
    if [ -e "/usr/bin/dorewan" ]; then
        chmod +x /usr/bin/dorewan
        /usr/bin/dorewan 2
    else
        logger "Auto REWAN: file missing, please reinstall.Settings don't work."
        sed -i '/dorewan/d' /etc/crontabs/root >/dev/null 2>&1 || exit 1
    fi
}

start()
{
	config_load autorewan
	config_foreach run_rewan main
}

stop()
{
	echo "Auto REWAN has stoped, but do nothing. if you need to clear setting, goto system -> autorewan and make it disable." > /tmp/autorewan.log
}
